In [5]:
# Pandas kütüphanesini import edelim.
import pandas as pd

In [6]:
#csv formatındaki datasetimizi içeri dahil edelim.
a = pd.read_csv("IMDB.csv")

In [7]:
#1  dosya hakkında bilgiler
a.columns

Index(['Movie_Title', 'YR_Released', 'Rating', 'Num_Reviews', 'Movie_ID',
       'Record'],
      dtype='object')

In [3]:
a.info

<bound method DataFrame.info of                                            Movie_Title  YR_Released  Rating  \
0                                    Code Name: K.O.Z.         2015     1.4
1                                     Saving Christmas         2014     1.5
2                         Superbabies: Baby Geniuses 2         2004     1.6
3                                    Daniel the Wizard         2004     1.6
4                             Manos: The Hands of Fate         1966     1.7
..                                                 ...          ...     ...
845  Pirates of the Caribbean: The Curse of the Bla...         2003     8.0
846                   What Ever Happened to Baby Jane?         1962     8.0
847                                       Paris, Texas         1984     8.0
848                                           Drishyam         2015     8.0
849                                                 PK         2014     8.0

     Num_Reviews   Movie_ID             Record
0          24623  tt4458206  Bottom 250 Movies
1          12765  tt4009460  Bottom 250 Movies
2          26505  tt0270846  Bottom 250 Movies
3          13295  tt0421051  Bottom 250 Movies
4          31808  tt0060666  Bottom 250 Movies
..           ...        ...                ...
845       872441  tt0325980     Top 250 Movies
846        37906  tt0056687     Top 250 Movies
847        55587  tt0087884     Top 250 Movies
848        40777  tt4430212     Top 250 Movies
849       106375  tt2338151     Top 250 Movies

[850 rows x 6 columns]>

In [4]:
a

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record
0,Code Name: K.O.Z.,2015,1.4,24623,tt4458206,Bottom 250 Movies
1,Saving Christmas,2014,1.5,12765,tt4009460,Bottom 250 Movies
2,Superbabies: Baby Geniuses 2,2004,1.6,26505,tt0270846,Bottom 250 Movies
3,Daniel the Wizard,2004,1.6,13295,tt0421051,Bottom 250 Movies
4,Manos: The Hands of Fate,1966,1.7,31808,tt0060666,Bottom 250 Movies
...,...,...,...,...,...,...
845,Pirates of the Caribbean: The Curse of the Bla...,2003,8.0,872441,tt0325980,Top 250 Movies
846,What Ever Happened to Baby Jane?,1962,8.0,37906,tt0056687,Top 250 Movies
847,"Paris, Texas",1984,8.0,55587,tt0087884,Top 250 Movies
848,Drishyam,2015,8.0,40777,tt4430212,Top 250 Movies
849,PK,2014,8.0,106375,tt2338151,Top 250 Movies

In [4]:
#2  ilk 5 kaydı gösterin
a[:5]

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record
0,Code Name: K.O.Z.,2015,1.4,24623,tt4458206,Bottom 250 Movies
1,Saving Christmas,2014,1.5,12765,tt4009460,Bottom 250 Movies
2,Superbabies: Baby Geniuses 2,2004,1.6,26505,tt0270846,Bottom 250 Movies
3,Daniel the Wizard,2004,1.6,13295,tt0421051,Bottom 250 Movies
4,Manos: The Hands of Fate,1966,1.7,31808,tt0060666,Bottom 250 Movies

In [5]:
#3  ilk 10 kaydı gösterin

a.head(10)

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record
0,Code Name: K.O.Z.,2015,1.4,24623,tt4458206,Bottom 250 Movies
1,Saving Christmas,2014,1.5,12765,tt4009460,Bottom 250 Movies
2,Superbabies: Baby Geniuses 2,2004,1.6,26505,tt0270846,Bottom 250 Movies
3,Daniel the Wizard,2004,1.6,13295,tt0421051,Bottom 250 Movies
4,Manos: The Hands of Fate,1966,1.7,31808,tt0060666,Bottom 250 Movies
5,Pledge This!,2006,1.7,15836,tt0417056,Bottom 250 Movies
6,Dünyayi Kurtaran Adam'in Oglu,2006,1.8,14110,tt0808240,Bottom 250 Movies
7,Foodfight!,2012,1.8,5740,tt0249516,Bottom 250 Movies
8,Birdemic: Shock and Terror,2010,1.8,15919,tt1316037,Bottom 250 Movies
9,Álom.net,2009,1.9,8502,tt1309000,Bottom 250 Movies

In [6]:
#4  son 5 kaydı gösterin
a.tail(5)

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record
845,Pirates of the Caribbean: The Curse of the Bla...,2003,8.0,872441,tt0325980,Top 250 Movies
846,What Ever Happened to Baby Jane?,1962,8.0,37906,tt0056687,Top 250 Movies
847,"Paris, Texas",1984,8.0,55587,tt0087884,Top 250 Movies
848,Drishyam,2015,8.0,40777,tt4430212,Top 250 Movies
849,PK,2014,8.0,106375,tt2338151,Top 250 Movies

In [7]:
#5  son 10 kaydı gösterin

a[-10:]

# 2.yöntem a.tail(10)

,Movie_Title,YR_Released,Rating,Num_Reviews,Movie_ID,Record
840,The Help,2011,8.0,345567,tt1454029,Top 250 Movies
841,Beauty and the Beast,1991,8.0,337665,tt0101414,Top 250 Movies
842,Dog Day Afternoon,1975,8.0,195760,tt0072890,Top 250 Movies
843,The Battle of Algiers,1966,8.0,41317,tt0058946,Top 250 Movies
844,In the Mood for Love,2000,8.0,84318,tt0118694,Top 250 Movies
845,Pirates of the Caribbean: The Curse of the Bla...,2003,8.0,872441,tt0325980,Top 250 Movies
846,What Ever Happened to Baby Jane?,1962,8.0,37906,tt0056687,Top 250 Movies
847,"Paris, Texas",1984,8.0,55587,tt0087884,Top 250 Movies
848,Drishyam,2015,8.0,40777,tt4430212,Top 250 Movies
849,PK,2014,8.0,106375,tt2338151,Top 250 Movies

In [8]:
#6  sadece Movie_Title kolonunu alın

a[["Movie_Title"]]

                                           Movie_Title
0                                    Code Name: K.O.Z.
1                                     Saving Christmas
2                         Superbabies: Baby Geniuses 2
3                                    Daniel the Wizard
4                             Manos: The Hands of Fate
..                                                 ...
845  Pirates of the Caribbean: The Curse of the Bla...
846                   What Ever Happened to Baby Jane?
847                                       Paris, Texas
848                                           Drishyam
849                                                 PK

[850 rows x 1 columns]

In [9]:
#7  Movie_Title kolonunu içeren ilk 5 kaydı alın.

a[["Movie_Title"]][:5]

                    Movie_Title
0             Code Name: K.O.Z.
1              Saving Christmas
2  Superbabies: Baby Geniuses 2
3             Daniel the Wizard
4      Manos: The Hands of Fate

In [10]:
#8  Sadece Movie_Title ve Rating kolonunu içeren ilk 5 kaydı alın.

a[["Movie_Title","Rating"]].head(5)

                    Movie_Title  Rating
0             Code Name: K.O.Z.     1.4
1              Saving Christmas     1.5
2  Superbabies: Baby Geniuses 2     1.6
3             Daniel the Wizard     1.6
4      Manos: The Hands of Fate     1.7

In [11]:
#9  Sadece Movie_Title ve Rating kolonunu içeren son 7 kaydı alın.

a[["Movie_Title","Rating"]].tail(7)

                                           Movie_Title  Rating
843                              The Battle of Algiers     8.0
844                               In the Mood for Love     8.0
845  Pirates of the Caribbean: The Curse of the Bla...     8.0
846                   What Ever Happened to Baby Jane?     8.0
847                                       Paris, Texas     8.0
848                                           Drishyam     8.0
849                                                 PK     8.0

In [12]:
#10  Sadece Movie_Title ve Rating kolonunu içeren ikinci 5 kaydı alın

a[["Movie_Title","Rating"]][5:10]

                     Movie_Title  Rating
5                   Pledge This!     1.7
6  Dünyayi Kurtaran Adam'in Oglu     1.8
7                     Foodfight!     1.8
8     Birdemic: Shock and Terror     1.8
9                       Álom.net     1.9

In [14]:
#11  Yayın tarihi 2014 ile 2015 arasında olan filmlerin isimlerini getiriniz.

a[(2014<=a.YR_Released) & (a.YR_Released<=2015)][["Movie_Title","YR_Released"]]

# 2.yöntem : a[(a["YR_Released"] >= 2014) & (a["YR_Released"] <= 2015)]["Movie_Title"]

                                    Movie_Title  YR_Released
0                             Code Name: K.O.Z.         2015
1                              Saving Christmas         2014
21                                 Potato Salad         2015
29                                   Humshakals         2014
49                              United Passions         2014
..                                          ...          ...
796                                   Spotlight         2015
797                          Mad Max: Fury Road         2015
814  Star Wars: Episode VII - The Force Awakens         2015
848                                    Drishyam         2015
849                                          PK         2014

[69 rows x 2 columns]

In [15]:
#12  Değerlendirme sayısı (Num_Rewies) 100.000 den büyük ya da imdb puanı 8 ile 9 arasında olan filmleri listeleyiniz.

a[(100000<=a.Num_Reviews) | ((8<=a.Rating) & (a.Rating<=9))][["Movie_Title","YR_Released","Rating","Num_Reviews"]]

,Movie_Title,YR_Released,Rating,Num_Reviews
100,The Shawshank Redemption,1994,9.2,1829037
101,The Godfather,1972,9.2,1249333
102,The Godfather: Part II,1974,9.0,860228
103,The Dark Knight,2008,9.0,1808543
104,12 Angry Men,1957,8.9,497242
...,...,...,...,...
845,Pirates of the Caribbean: The Curse of the Bla...,2003,8.0,872441
846,What Ever Happened to Baby Jane?,1962,8.0,37906
847,"Paris, Texas",1984,8.0,55587
848,Drishyam,2015,8.0,40777
849,PK,2014,8.0,106375